function path(root, sublink) {
  return `${root}${sublink}`;
}
const ROOTS_DASHBOARD = "/dashboard";

const paths = {
  signin: "/signin",
  resetpassword: "/resetpassword",
  newPassword: "/NewPassword/:token_id",
  dashboard: "/dashboard",
  mainDashboard: path(ROOTS_DASHBOARD, "/main"),
  users: path(ROOTS_DASHBOARD, "/users"),
  clients: path(ROOTS_DASHBOARD, "/clients"),
  rolepermission: path(ROOTS_DASHBOARD, "/roleandpermission"),
  role: path(ROOTS_DASHBOARD, "/role"),
  Profile: path(ROOTS_DASHBOARD, "/profile"),
  companies: path(ROOTS_DASHBOARD, "/companies"),
  competencesettings: path(ROOTS_DASHBOARD, "/competencesettings"),
  clientSites: path(ROOTS_DASHBOARD, "/clientssites&projects"),
  localization: path(ROOTS_DASHBOARD, "/localization"),
  clientPreferences: path(ROOTS_DASHBOARD, '/Languages/ClientPreferences'),
  competence: path(ROOTS_DASHBOARD, '/Competence'),
  workerDocuments: path(ROOTS_DASHBOARD, '/Competence/WorkerDocuments'),
  // Elearning
  emailTemplate: path(ROOTS_DASHBOARD, "/emailTemplate"),
  addEmailTemplate: path(ROOTS_DASHBOARD, "/addEmailTemplate"),
  workerDashboard: path(ROOTS_DASHBOARD, "/workerDashboard"),
  myTranings: path(ROOTS_DASHBOARD, "/my-tranings"),
  MySeries: path(ROOTS_DASHBOARD, "/my-series"),
  safetyCertificate: path(ROOTS_DASHBOARD, "/safetyCertificate"),
  categories: path(ROOTS_DASHBOARD, "/categories"),
  topics: path(ROOTS_DASHBOARD, "/topics"),
  externalTraning: path(ROOTS_DASHBOARD, "/externalTraning"),
  requiredDocuments: path(ROOTS_DASHBOARD, "/requiredDocuments"),
  department: path(ROOTS_DASHBOARD, "/department"),
  function: path(ROOTS_DASHBOARD, "/function"),
  startQuiz: path(ROOTS_DASHBOARD, "/startQuiz"),
  quizInstructions: path(ROOTS_DASHBOARD, "/quizInstructions"),
  trueFalse: path(ROOTS_DASHBOARD, "/trueFalse"),
  multipleChoice: path(ROOTS_DASHBOARD, "/multipleChoice"),
  dragDropSorting: path(ROOTS_DASHBOARD, "/dragDropSorting"),
  dragDropIntrective: path(ROOTS_DASHBOARD, "/dragDropIntrective"),
  freeText: path(ROOTS_DASHBOARD, "/freeText"),
  underReview: path(ROOTS_DASHBOARD, "/underReview"),
  passedQuiz: path(ROOTS_DASHBOARD, "/passedQuiz"),
  failedQuiz: path(ROOTS_DASHBOARD, "/failedQuiz"),
  certificate: path(ROOTS_DASHBOARD, "/certificate"),
  invoiceHistory: path(ROOTS_DASHBOARD, "/invoiceHistory"),
  invoice: path(ROOTS_DASHBOARD, "/invoice"),
  checkout: path(ROOTS_DASHBOARD, "/checkout"),
  tranings: path(ROOTS_DASHBOARD, "/tranings"),
  training_detail: path(ROOTS_DASHBOARD, "/training_detail"),
  traningSeries: path(ROOTS_DASHBOARD, "/traning-series"),
  traningDetailModal: path(ROOTS_DASHBOARD, "/tranings-details"),
  viewParticipant: path(ROOTS_DASHBOARD, "/viewParticipant"),
  singleAddNewTraning: path(ROOTS_DASHBOARD, "/singleAddNewTraning"),
  multipleAddNewTraning: path(ROOTS_DASHBOARD, "/multipleAddNewTraning"),
  assignment: path(ROOTS_DASHBOARD, "/assignment"),
  adminDashboard: path(ROOTS_DASHBOARD, "/adminDashboard"),
  subContractor: path(ROOTS_DASHBOARD, "/subContractor"),
  polices: path(ROOTS_DASHBOARD, "/polices"),
  fieldManagement: path(ROOTS_DASHBOARD, "/fieldManagement"),
  information: path(ROOTS_DASHBOARD, '/Information'),
  classifications: path(ROOTS_DASHBOARD, '/Information/Classifications'),
  categories: path(ROOTS_DASHBOARD, '/Information/Categories'),
  subCategories: path(ROOTS_DASHBOARD, '/Information/SubCategories'),
  tags: path(ROOTS_DASHBOARD, '/Information/Tags'),
  status: path(ROOTS_DASHBOARD, '/Information/Status'),


};
export default paths;
