// export const BASE_URL = process.env.REACT_APP_BACKEND_URL_LIVE;
 export const BASE_URL = "https://newelearning.safetytracker.be/public/api/"; // Dev
// export const BASE_URL = "http://elearningproapis.safetytracker.be/public/api/"; // Production

//  export const BASE_URL = "http://192.168.18.13/ElearningWebServices/public/api/";
export const API_END_POINTS = {
  login: BASE_URL + "login",
  updateProfile: BASE_URL + "management/profile/update",
  language: BASE_URL + "languages",
  languageDropDown: BASE_URL + "all-languages",
  nativeOtherLangaugesDropdown: BASE_URL + "management/user/get-languange",
  languageTranslation: BASE_URL + "keyword-languages",
  setAdminDefaultLanguage: BASE_URL + "admin-default-language",
  keywordTranslationUpload: BASE_URL + "keyword-translation-import",
  updateLanguageStatus: BASE_URL + "language-status-update",
  createCompany: BASE_URL + "management/company/create",
  managementCompanyList: BASE_URL + "management/company/show",
  updateStatusCompany: BASE_URL + "management/company/update-status",
  forgetpassword: BASE_URL + "forget-password",
  resetPassword: BASE_URL + "reset-password",
  updatePassword: BASE_URL + "management/profile/password-update",
  logout: BASE_URL + "logout",
  getProject: BASE_URL + "management/project/get",
  addProject: BASE_URL + "management/project/add",
  deleteProject: BASE_URL + "management/project/delete",
  updateProject: BASE_URL + "management/project/update",
  siteProject: BASE_URL + "management/site/get",
  getZone: BASE_URL + "management/zone/get",
  addZone: BASE_URL + "management/zone/add",
  deleteZone: BASE_URL + "management/zone/delete",
  getRoleList: BASE_URL + "role",
  roleDropDown: BASE_URL + "role/drop-down/web",
  newRoleDropDown: BASE_URL + "role/auth-drop-down/web",
  addNewRole: BASE_URL + "role",
  companyRolePermission: BASE_URL + "role/company-role-with-permissions",
  giveRolePermission: BASE_URL + "role/give-permission-to-role",
  revokeRolePermission: BASE_URL + "role/revoke-permission-to-role",
  clientAdd: BASE_URL + "management/client/add",
  clientSiteUpdate: BASE_URL + "management/client/update",
  clientSiteDelete: BASE_URL + "management/client/delete",
  updateCompany: BASE_URL + "management/company/update",
  getCompanyPermission: BASE_URL + "company-permission",
  deleteCompany: BASE_URL + "management/company/delete",
  createFunction: BASE_URL + "management/company/function/add",
  getFunctions: BASE_URL + "management/company/function/get",
  createDepartment: BASE_URL + "management/company/department/add",
  getDepartments: BASE_URL + "management/company/department/get",
  componyDropDownList: BASE_URL + "management/company/drop-down",
  siteDropdown: BASE_URL + "management/site/drop-down",
  siteDelete: BASE_URL + "management/site/delete",
  siteUpdate: BASE_URL + "management/site/update",
  clientDropdown: BASE_URL + "management/client/drop-down",
  functionDropdown:
    BASE_URL + "management/company/function/drop-down?company_id=",
  departmentDropdown:
    BASE_URL + "management/company/department/drop-down?company_id=",
  companyRoleDropdown: BASE_URL + "management/company/role/drop-down",
  permissionsList: BASE_URL + "permission?per_page=100",
  permissionDropdown: BASE_URL + "permission-drop-down",
  createEntities: BASE_URL + "management/company/entity/add",
  getEntities: BASE_URL + "management/company/entity/get",
  createUser: BASE_URL + "management/user/add",
  updateUser: BASE_URL + "management/user/update",
  getUsers: BASE_URL + "management/user/list",
  deleteUser: BASE_URL + "management/user/delete",
  updateUserStatus: BASE_URL + "management/user/status",
  updateClientPreferences: BASE_URL + "prefrences-update/",
  getClients: BASE_URL + "management/client/get",
  addSites: BASE_URL + "management/site/add",
  updateRole: BASE_URL + "role",
  userListDropDown: BASE_URL + "management/user/user-list-drop-down",
  managerDropDown: BASE_URL + "management/user/manager-drop-down?company_id=",
  reportToDropDown:
    BASE_URL + "management/user/report-to-drop-down?company_id=",
  entityDropdown:
    BASE_URL + "management/company/child-company-drop-down?company_id=",
  deleteDepartment: BASE_URL + "management/company/department/delete",
  updateDepartment: BASE_URL + "management/company/department/update",
  deleteFunction: BASE_URL + "management/company/function/delete",
  updateFunction: BASE_URL + "management/company/function/update",
  addCategoryCompetence:
    BASE_URL + "management/competence-setting/category/add",
  getCategoryCompetence:
    BASE_URL + "management/competence-setting/category/show",
  updateCategoryCompetence:
    BASE_URL + "management/competence-setting/category/update",
  deleteCategoryCompetence:
    BASE_URL + "management/competence-setting/category/delete",
  categoryCompetenceDropdown:
    BASE_URL + "management/competence-setting/category/dropdown?company_id=",
  addTopic: BASE_URL + "management/competence-setting/topic/add",
  getTopic: BASE_URL + "management/competence-setting/topic/get",
  updateTopic: BASE_URL + "management/competence-setting/topic/update",
  deleteTopic: BASE_URL + "management/competence-setting/topic/delete",
  topicDropdown: BASE_URL + "management/competence-setting/topic/dropdown",
  addCertificate:
    BASE_URL + "management/competence-setting/required-certificate/add",
  getCertificates:
    BASE_URL + "management/competence-setting/required-certificate/get",
  deleteCertificate:
    BASE_URL + "management/competence-setting/required-certificate/delete",
  updateCertificate:
    BASE_URL + "management/competence-setting/required-certificate/update",
  updateStatusCertificate:
    BASE_URL +
    "management/competence-setting/required-certificate/required-status",
  addDocument: BASE_URL + "management/competence-setting/required-document/add",
  getDocuments:
    BASE_URL + "management/competence-setting/required-document/get",
  deleteDocuments:
    BASE_URL + "management/competence-setting/required-document/delete",
  updateDocument:
    BASE_URL + "management/competence-setting/required-document/update",
  updateStatusDocument:
    BASE_URL +
    "management/competence-setting/required-document/required-status",
  crudStatus: BASE_URL + "management/information/status",
  crudTypes: BASE_URL + "management/information/type",
  typeDropdown: BASE_URL + "management/information/type-dropdown",
  crudClassification: BASE_URL + "management/information/classification",
  crudCategories: BASE_URL + "management/information/category",
  infoCategoriesDropdown:
    BASE_URL + "management/information/category/drop-down",
  crudBrands: BASE_URL + "brand",
  crudScafoldingCatagories: BASE_URL + "element-category",
  crudInfoSubCategories: BASE_URL + "management/information/subcategory",
  infoSubCategoriesDropdown:
    BASE_URL + "management/information/subcategory/drop-down",
  crudInfoTags: BASE_URL + "management/information/tag",
  crudSiteInspections: BASE_URL + "template",
  crudLmra: BASE_URL + "lmra",
  getSingleLmra: BASE_URL + "lmra/show",
  lmraTemplateDropdown: BASE_URL + "lmra/dropdown",
  lmraWebDashboard: BASE_URL + "lmra-web-dashboard",
  lmraDashboardGraph: BASE_URL + "lmra-dashboard-graph",
  projectDropdown: BASE_URL + "management/project/drop-down",
  lmraInspectionReport: BASE_URL + "lmra-inspection-report",
  assignLmraInspection: BASE_URL + "lmra-assign-inspection",
  approveLmraAssignment: BASE_URL + "lmra-approve-assignment",
  getAllTraining: BASE_URL + "training",
  deleteTraining: BASE_URL + "training",
  addTraining: BASE_URL + "training",
  addCommentOnTraining: BASE_URL + "training/add-note",
  deleteCommentOnTraining: BASE_URL + "training/delete-note",
  updateCommentOnTraining: BASE_URL + "edit-note",
  getSingleTrainingList: BASE_URL + "training/single-list",
  getTrainingDetails: BASE_URL + "worker/training-detail",
  addSeriesTraining: BASE_URL + "series-training",
  getSeriesTraining: BASE_URL + "series-training",
  deleteSeriesTraining: BASE_URL + "series-training",
  singleSeriesTraining: BASE_URL + "single-series-training",
  departmentDropdownList: BASE_URL + "management/company/department/drop-down",
  seriesTrainingList: BASE_URL + "series-section-list",
  workerSubmitQuiz: BASE_URL + "worker/submit-quiz",
  getTeacherTraining: BASE_URL + "teacher-training",
  teacherTrainingQuestion: BASE_URL + "teacher-training-question",
  teacherTrainingRemarks:
    BASE_URL + "teacher-training-question-teacher-remarks",
  purchaseTraining: BASE_URL + "worker/purchase-training",
  updateQrCode: BASE_URL + "management/profile/update-qrcode",
  importCSVFile: BASE_URL + "management/profile/import-users",
  workerBadgeSettings: BASE_URL + "management/company/worker-badge-setting",
  updateCompanyAdvance:
    BASE_URL + "management/company/update-company-advance-view",
  getTopicCerts: BASE_URL + "certificate/certificate",
  getTopicDocuments: BASE_URL + "UserCertificate/user-documents-web",
  getTopicDocumentsProfile: BASE_URL + "UserCertificate/user-documents-web",
  getSingleUserDetail: BASE_URL + "management/user/single-user",
  crudTopicDocuments: BASE_URL + "document/document",
  crudTopicCertificates: BASE_URL + "certificate/certificate",
  deleteUserProfileDocument: BASE_URL + "document/document",
  deleteUserProfileCertificate: BASE_URL + "certificate/certificate",
  addPinCode: BASE_URL + "v1/mobile/management/add-pin",
  updatePinCode: BASE_URL + "v1/mobile/management/update-pin",
  downloadTrainingCertificate:
    BASE_URL + "download-certificate",
};
