export let english = {
    "id": 1,
    "name": "English",
    "language_direction": 0,
    "abbrevation": "en",
    "keywordTranslation": {
        'Dashboard': 'Dashboard',
        'Observations': 'Observations',
        "Language": "Language",
        "English": "English",
        "French": "French",
        "Dutch": "Dutch",
        "German": "German",
        "Profile": "Profile",
        "Settings": "Settings",
        "Theme": "Dark Mode",
        "Enabled": "Enabled",
        "Disabled": "Disabled",
        "Notification": "Notifications",
        "Nonotification": "No Notifications Found!",
        "Pincode": "Pin Code",
        "Help": "Help",
        "Terms": "Terms & Conditions",
        "Privacy": "Privacy Policy",
        "Feedback": "Leave feedback",
        "Logout": "Logout",
        "Signin": "Sign In",
        "Search country code": "Search",
        "searchStartCountryCode": "Start typing to search",
        "Managesignin": "Sign in to manage your account",
        "NewtbmR": "New TBM",
        "Signin scan": "Scan to Sign in",
        "Sign with email": "Or sign in with your email",
        "Email address": "Email Address",
        "Password": "Password",
        "Forget": "Forgot Password?",
        "Remember": "Remember me",
        "Bsignin": "SIGN IN",
        "Noaccount": "Don't have an account yet?",
        "Signup": "SignUp Now",
        "Credentials text error": "These credentials do not match our records.",
        "Verify email": "Please verify you email",
        "Enter email": "Enter your email address",
        "Enter password": "Enter your password",
        "Valid email": "Please enter a valid email address",
        "Error email": "Please enter your email address",
        "Error pass": "Please enter your password",
        "Valid pass": "Password must contains at least 8 characters,including uppercase, lowercase, number and symbols.",
        "Sign Ups": "Sign Up",
        "Sign up text": "Sign up for a new safety experience.",
        "COMPANY": "COMPANY",
        "Select companyw": "Select the company you work for",
        "ROLE": "ROLE",
        "Select Role": "Select Role",
        "FIRST NAME": "FIRST NAME",
        "Hfname": "Enter your first name",
        "Lastnname": "Last Name",
        "Hlname": "Enter your last name",
        "Already Registered": "Your email is already Registered",
        "Cpassword": "Confirm password",
        "Rpassword": "Repeat password",
        "Error text company": "Please select company",
        "Slectbrch": "Select a entity",
        "Entity": "Entity",
        "Pin not matched error": "Please try again.",
        "Pin not matched error2": "Go to your profile and set your PIN code.",
        "Error text branch": "Please select a entity",
        "Error text role": "Please select Role",
        "Error text fname": "Please enter first name",
        "Error text lname": "Please enter last name",
        "Both password": "Both passwords are not matching",
        "Bsign up": "SIGN UP",
        "Already account": "Already have an account?",
        "Sign in now": "Sign In Now",
        "Welcome": "Welcome",
        "Instantob": "Instant Observations",
        "Tbm": "ToolBox Meetings",
        "Sinspection": "Site Inspections",
        "LMRA": "LMRA",
        "Competency": "Competency Matrix",
        "Draw signature": "Draw signature",
        "Up load image": "Upload image",
        "Select Company": "Select Company",
        "Select Function": "Select Function",
        "Update success": "Update Success",
        "Edit profile": "Edit Profile",
        "Signature": "Signature",
        "Questionans": "Questions answered",
        " Edit": "Edit",
        "Reportto": "Report To",
        "Selectdepart": "Select Department",
        "DEPARTMENT": "DEPARTMENT",
        "lfunction": "Function",
        "Enter number": "Enter Number",
        "Year": "Year",
        "Month": "Month",
        "Day": "Day",
        "Phone": "Phone",
        "BIRTHDAY": "BIRTHDAY",
        "Jan": "jan",
        "Feb": "feb",
        "Mar": "mar",
        "Apr": "apr",
        "May": "may",
        "Jun": "jun",
        "Jul": "jul",
        "Aug": "aug",
        "Sep": "sep",
        "Oct": "oct",
        "Nov": "nov",
        "Dec": "dec",
        "notbm": "No TBMs Found!",
        "Notbntxt": "Try different keywords or clear your filters.",
        "Reject": "Rejected",
        "Rejected large": "REJECTED",
        "Remaining": "Remaining",
        "Remainingl": "REMAINING",
        "Completedl": "COMPLETED",
        "Completed": "Completed",
        "Oldest": "Oldest",
        "Newest": "Newest",
        "Tbmmeting": "ToolBox Meetings",
        "Hours ago": "hours ago",
        "Hour ago": "hour ago",
        "Days ago": "days ago",
        "Day ago": "day ago",
        "Weeks ago": "weeks ago",
        "Week ago": "week ago",
        "Minutes ago": "minutes ago",
        "Minute ago": "minute ago",
        "Seconds ago": "seconds ago",
        "Months ago": "months ago",
        "Month ago": "month ago",
        "Years ago": "years ago",
        "Year ago": "year ago",
        "Year left": "YEAR LEFT",
        "Over due": "Overdue",
        "Day left": "DAY LEFT",
        "Days left": "DAYS LEFT",
        "Monthleft": "MONTH LEFT",
        "Deadline": "Deadline",
        "Submit": "Submit",
        "Invalidsubmit": "You can't submit without solving TBM Quiz",
        "AddSignature": "Please Add a Signature from Edit Profile",
        "Addpin": "Please Add a pin",
        "Verifysignature": "Click to verify signature",
        "Tbmquiz": "TBM Quiz",
        "Tbmpost": "TBM",
        "Done": "Done",
        "Nosignature": "You don't have any signature.To add signature press edit button",
        "Pinverified": "Pin Code Verified",
        "Back": "Back",
        "Tryagain": "Please try again.",
        "Codenotvalid": "Pin Code Is Not Valid!",
        "Quiznotsubmit": "Your Quiz is not submitted",
        "Quizsubmitforcheck": "Your ToolBox Meetings has been sent for verification. You can check your TBMs through the history.",
        "Cancel": "Cancel",
        "Confirm": "Confirm",
        "Inspection": "New Inspection",
        "Totalinspections": "Total inspections",
        "Failed": "Failed",
        "Lastinspection": "Last inspection",
        "April": "44294",
        "Nextinspection": "Next inspection",
        "Generalsafetychecklist": "General Workplace Safety Checklist",
        "Clientname": "Client Name",
        "Sitename": "Site Name",
        "Sitenameo": "Sitename",
        "Projectname": "Project Name",
        "Passed": "Passed",
        "Nositeinspectionfound": "No Site Inspection Found!",
        "History": "History",
        "Inspectionreport": "Inspection Report",
        "Safety": "Safety",
        "Tracker": "Tracker",
        "By": "By",
        "Username": "User Name",
        "Client": "Client",
        "Site": "Site",
        "Project": "Project",
        "Media": "Media",
        "No": "NO",
        "Questiontext": "Question Text",
        "Comment": "Comment",
        "General comment": "General comment",
        "Comments": "Comments",
        "Yes": "yes",
        "Additionalcomment": "Additional Comment",
        "Addmedia": "Add Media",
        "Takepicture": "Take picture",
        "recordvideo": "Record video",
        "Browse gallery": "Browse gallery",
        "New Inspection": "New Inspection",
        "Checklist": "Checklist",
        "Topic1": "Topic1",
        "Topic2": "Topic2",
        "Topic3": "Topic3",
        "Topic4": "Topic4",
        "Topic5": "Topic5",
        "Topic6": "Topic6",
        "Topic7": "Topic7",
        "Topic8": "Topic8",
        "File Type": "File Type",
        "Type here, or press the button to start dictation": "Type here, or press the button to start dictation",
        "Add Signature": "Add Signature",
        "search": "search",
        "Location service sare disabled": "Location services are disabled",
        "Location permissions denied": "Location permissions are denied",
        "location permissions permanently denied": "Location permissions are permanently denied, we cannot request permissions.",
        "permission granted": "Permission granted",
        "Select client": "Select client",
        "Selected clint id": "SelectedClintId",
        "Select site": "Select site",
        "Select project": "Select project",
        "select your location": "Select your location",
        "Location services disabled": "Location Services disabled",
        "Next": "Next",
        "Please select client": "Please select client",
        "Please select site": "Please select site",
        "Please select project": "Please select project",
        "New Password": "New Password",
        "Enter the new password": "Enter the new password",
        "Enter your new Password": "Enter your new Password",
        "Confirm new password": "Confirm new password",
        "ConfirmL": "CONFIRM",
        "Reset password": "Reset Password",
        "Enter thee mail associated with your account": "Enter the email associated with your account and we will send an email with instructions",
        "Could not find user email address": "We could not find a user with that email address",
        "Field is empty": "Field is empty",
        "Send": "SEND",
        "Didn't receive reset password": "Didn't receive the reset password link?",
        "Resend now": "Resend Now",
        "All": "All",
        "Daily": "Daily",
        "Monday": "Mon",
        "Tuesday": "Tue",
        "Wednesday": "Wed",
        "Thursday": "Thu",
        "Frida": "Fri",
        "Saturday": "Sat",
        "Sunday": "Sun",
        "Sales": "Sales",
        "Filter": "Filter",
        "Newestl": "newest",
        "Filter by": "Filter by",
        "Weekly": "Weekly",
        "Monthly": "Monthly",
        "Yearly": "Yearly",
        "Clear": "Clear",
        "Date": "Date",
        "Type": "Type",
        "Status": "Status",
        "Category": "Category",
        "Subcategory": "Subcategory",
        "Tags": "Tags",
        "Statuso": "Status",
        "Categoryo": "Category",
        "Subcategoryo": "Subcategory",
        "Tagso": "Tags",
        "Filter by date": "Filter by date",
        "Filter by type": "Filter by type",
        "Quality": "Quality",
        "Environment": "Environment",
        "Filter by category": "Filter by category",
        "Filter by subcategory": "Filter by Subcategory",
        "Filter by tags": "Filter by tags",
        "Conformity": "Conformity",
        "Not adapted": "Not adapted",
        "Badcondition": "Bad condition",
        "Expired used": "Expired / used",
        "Used": "used",
        "Waterproof": "Waterproof",
        "Filter by status": "Filter by status",
        "Excellent": "Excellent",
        "Good": "Good",
        "Minor": "Minor",
        "Moderate": "Moderate",
        "Major": "Major",
        "Critical": "Critical",
        "Incident": "Incident",
        "Idea": "Idea",
        "Other": "Other",
        "My observations": "My Observations",
        "Statistics": "Statistics",
        "Rejected observations": "Rejected observations",
        "Tracking information": "Tracking Information",
        "Inqueue": "IN QUEUE",
        "Observation submitted back online": "Your observation will be submitted once you get back online.",
        "Pending": "PENDING",
        "Observation submitted": "Your observation has been submitted successfully",
        "In progress": "In Progress",
        "Observation accepted work": "Your observation has been accepted by the",
        "Resolved": "RESOLVED",
        "Solvedc": "Solved",
        "Closeddc": "Closed",
        "Closed": "CLOSED",
        "Observation closed": "Observation has been closed.",
        "Download file": "Downloading File:",
        "Worker pin code before scanning": "Please let the worker enter his PIN Code before scanning his QR Code",
        "Inspection submitted": "Inspection submitted successfully",
        "Inspection not submitted": "Inspection not submitted. Please try again",
        "Select an action": "Please select an option.",
        "Take photo or video": "Take a photo, record a video or upload",
        "Right": "Right",
        "Wrong": "Wrong",
        "Not know": "NA",
        "Ok": "OK",
        "Na": "NA",
        "Rejected": "Rejected",
        "Solved": "SOLVED",
        "Search observations": "Search observations",
        "search tbm": "Search Tbm",
        "Mechanical engineer": "Mechanical Engineer",
        "FUNCTION": "FUNCTION",
        "No observation found": "No Observation Found!",
        "addcomment": "Add a comment",
        "Electrician": "Electrician",
        "Reply": "Reply",
        "Likes": "Likes",
        "Like": "Like",
        "Replies": "Replies",
        "Observation title": "Observation Title",
        "titlehere": "Title here...",
        "Title": "Title",
        "Upload photo video": "Take a photo, record a video or upload",
        "mode": "Mode",
        "Public": "Public",
        "Private": "Private",
        "Pleaseent ertitle": "Please enter title",
        "Select image video": "Please select image/video",
        "Enter description": "Please enter description",
        "New observation": "New Observation",
        "Classification": "Classification",
        "Classification type": "Classification type",
        "Category name": "Category name",
        "Subcategory name": "Subcategory name",
        "Required": "Required",
        "Assign to": "Assign To",
        "Select manager": "Select Manager",
        "Select classification": "Please select classification",
        "Select category": "Please select category",
        "Select sub category": "Please select subcategory",
        "Select Status": "Select Status",
        "Please select manager": "Please select manager",
        "Error textetype": "Please select type",
        "Overview": "Overview",
        "Change pin": "Change PIN Code",
        "Set pin": "Set PIN Code",
        "Promoted to enter code": "You will be prompted to enter this code each time your signature is required.",
        "Current pin": "Current PIN Code",
        "New pin": "New PIN Code",
        "Confirm pin": "Confirm PIN Code",
        "Error current pin": "Please enter current pin",
        "Error enter new pin": "Please enter new pin",
        "Both pin not match": "Both pins are not matched !",
        "Server error": "Server Error",
        "Observation details": "Observation Details",
        "Rejected reason": "Rejected Reason",
        "Observation tracker": "Observation Tracker",
        "Observation rejected": "Your observation has been rejected by the",
        "Observation accepted": "Your observation has been accepted by the",
        "Observation resolved": "Your observation has been resolved by the",
        "Offline now": "You are Offline Right Now!",
        "changePINcode": "Change PIN Code",
        "Prompted to code signature required": "You will be prompted to enter this code each time your signature is required",
        "Data saved once you back online": "Don't worry, your data was saved and will be submitted once you get back online",
        "Current pin code": "Current PIN Code",
        "New pin code": "New PIN Code",
        "Confirm pin code": "Confirm PIN Code",
        "Please enter current pin": "Please enter current pin",
        "Please enter new pin": "Please enter new pin",
        "Both pins not matched": "Both pins are not matched",
        "Save": "Save",
        "Scan QR code": "Scan QR Code",
        "Scan QR code you got from your company": "Scan the QR Code you got from \n  your company",
        "Your company": "your company",
        "No permission": "no Permission",
        "Status information": "Status Information",
        "Submitted successfully": "Submitted Successfully",
        "Inspection not submitted Message": "Your Inspection has been submitted. You can check your report through the history.",
        "See more": "see more",
        "See less": "see less",
        "Loading": "Loading",
        "Select equipment": "Select equipment",
        "select rooms": "Select rooms",
        "Select zone": "Select zone",
        "Select room": "Select room",
        "Selected site": "Select a site",
        "Zone": "Zone",
        "Move back screen error": "If you want to move to back screen then data you choose will be lost.",
        "Level": "Level",
        "Back button": "Back",
        "Cancel Button": "Cancel",
        "Room": "Room",
        "Equipment": "Equipment",
        "Assignments": "Assignments",
        "Equipment name": "Equipment name",
        "Error text equipment": "Please select equipment",
        "Error text level": "Please select a level",
        "Error text room": "Please select room",
        "Error text zone": "Please select zone",
        "Not reported": "Not reported",
        "Location": "Location",
        "Verify informattion": "Verify Your Information",
        "Choose template": "Choose Template",
        "Select temp": "Select template you want to use for this Assessment.",
        "Temp error": "Please select a template",
        "Continue": "Continue",
        "Slct": "Select",
        "New lrma": "New LMRA",
        "Asignature": "Add Signature",
        "Draw": "Draw",
        "Crop": "Crop",
        "Undo": "Undo",
        "Total lmra": "Total LMRAs",
        "Last lmra": "Last LMRA",
        "Last minutes risk": "Last Minute Risk Assignment Checklist",
        "No lmra found": "NO LMRA found",
        "Lmra report": "LMRA Report",
        "Under review": "Under review",
        "Team member": "Team Members",
        "Work procedure": "Work Procedure",
        "Can work": "Can Work",
        "Cant work": "Can't Work",
        "Result": "Result",
        "Change password": "Change Password",
        "Pass text": "Change Your Password",
        "Current password": "Current Password",
        "Confirm password": "Confirm Password",
        "Error current pass": "Please enter current Password",
        "Error enter new pass": "Please enter new Password",
        "Both pass not match": "Both Password are not matched !",
        "Search manager": "Search managers",
        "Reassign": "Reassign",
        "Search worker": "Search workers",
        "Addw": "Add",
        "Approved": "Approved",
        "Checked": "Checked",
        "Reassigned to": "Reassigned To",
        "Rjt": "Reject",
        "Approve": "Approve",
        "Req of approve": "Request for Approval",
        "In progresss": "IN PROGRESS",
        "Work error procedure": "Please Enter Work Procedure",
        "Error add team": "Please Add Team Members",
        "Submit capital": "SUBMIT",
        "Piease select all question": "Please attempt all questions!",
        "Question error": "Please Select Answers",
        "Error text verified worker": "Only worker With Signature can be added!",
        "Add member": "Add Members",
        "Verify sig": "Verify Signature",
        "No worker lmra": "No workers for this LMRA yet",
        "Ok work": "Ok! You Can Work",
        "Under review work": "Please wait! Your LMRA is under review",
        "Cannot work": "STOP! You Can’t Work",
        "Work value": "Your LMRA has been submitted. You can check your report through the history.",
        "Cannot work value": "You can do another task until you are contacted by the safety department.",
        "Under review work value": "The managers you have assigned the LMRA to will review your request and let you know whether you can start working or not.",
        "Approve text": "Are you sure you want to accept this assignment?",
        "Approve reason": "Accepting this assignment means that the solution proposed by the manager is a good solution.",
        "Reject text": "Are you sure you want to reject this assignment?",
        "Reject reason": "If yes, Please describe why:",
        "Pin sig not found": "You Don\\'t have any Signature.Please add signature from profile",
        "Show more": "See More...",
        "Show less": "See Less..",
        "Image viewer": "Picture Viewer",
        "No workers": "No Workers",
        "Move back edit screen error": "You have to select Function, Date of birth and Department to Proceed.",
        "Type here": "Type here",
        "Add equipment": "Add equipment",
        "Reassigned": "Reassigned",
        "Search result": "Search Result",
        "Enter description text200": "Description must contain minimum 3 characters",
        "Select data": "You have to select",
        "To procede": "to Proceed.",
        "And depart": "and Department",
        "Dobs": "Date of birth",
        "Name": "Name",
        "Already submit": "You have already submitted the quiz",
        "Updateobs": "Update Observation",
        "Updatebtn": "Update",
        "No certificate found": "No Certificate Found!",
        "No documents found": "No Documents Found!",
        "No data": "No data found",
        "Search classification": "Search Classification",
        "Search category": "Search Category",
        "Search subcategory": "Search SubCategory",
        "Search client": "Search Client",
        "Search site": "Search Site",
        "Search project": "Search Project",
        "Search zone": "Search Zone",
        "Alert": "Alert",
        "Describe procedure": "Describe your procedure in a few words.",
        "Alert first time": "You need to login with email and password for the first time",
        "USERS": "USERS",
        "Clients": "Clients",
        "Observation": "Observation",
        "Tool box meetings": "Tool box meetings",
        "Site Inspections": "Site Inspections",
        "Competence": "Competence",
        "Role and permissions": "Role and permissions",
        "App iocalization": "App iocalization",
        "Clients,sites and projects": "Clients,sites and projects",
        "Companies": "Companies",
        "Competence Settings": "Competence Settings",
        "Observations all": "Observations all",
        "Total users": "Total users",
        "Users average age": "Users average age",
        "Users top functions": "Users top functions",
        "Active users": "Active users",
        "Users": "Users",
        "Inactive users": "Inactive users",
        "Search by id document": "Search by id document",
        "Select age": "Select age",
        "Select user": "Select user",
        "Select Department": "Select Department",
        "Select report to": "Select report to",
        "Age": "Age",
        "EMAIL": "EMAIL",
        "New user": "New user",
        "Clear filter": "Clear filter",
        "No record found": "No record found",
        "Edit": "Edit",
        "ToolBox Meetings": "ToolBox Meetings",
        "MANAGE": "MANAGE",
        "Clients (Super Admin)": "Clients (Super Admin)",
        "Roles & Permissions": "Roles & Permissions",
        "Field Management": "Field Management",
        "App localization": "App localization",
        "Clients, Sites & Projects": "Clients, Sites & Projects",
        "Informations": "Informations",
        "©SafetyTracker 2021 | A huge step towards the 0 harm goal…": "©SafetyTracker 2021 | A huge step towards the 0 harm goal…",
        "New user +": "New user +",
        "Print Badges": "Print Badges",
        "Import csv file": "Import csv file",
        "User has been created successfully.": "User has been created successfully.",
        "User's status has been updated successfully.": "User's status has been updated successfully.",
        "User(s) has been deleted successfully.": "User(s) has been deleted successfully.",
        "User has been updated successfully.": "User has been updated successfully.",
        "Search by id, document …": "Search by id, document …",
        "Clear filters": "Clear filters",
        "User": "User",
        "N+1": "N+1",
        "Action": "Action",
        "Activate": "Activate",
        "Deactivate": "Deactivate",
        "Delete": "Delete",
        "IMAGE": "IMAGE",
        "Drag and drop your file here": "Drag and drop your file here",
        "Or": "Or",
        "browse files": "browse files",
        "LAST NAME": "LAST NAME",
        "ACRONYM": "ACRONYM",
        "PHONE NUMBER": "PHONE NUMBER",
        "Select Entity": "Select Entity",
        "NATIVE LANGUAGE": "NATIVE LANGUAGE",
        "Select Language": "Select Language",
        "[+] Add new": "[+] Add new",
        "OTHER LANGUAGES": "OTHER LANGUAGES",
        "Update": "Update",
        "Create": "Create",
        "Users will be created": "Users will be created",
        "Only active users": "Only active users",
        "FROM": "FROM",
        "optional": "optional",
        "TO": "TO"
    }
}