on: 
  push:
    branches:
      - gh-pages
name: 🚀 Uploading Build
permissions: 
  contents: write
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server:  ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
  
    # - name: Moving build to artifacts directory
    #   run: |
    #     chmod +x ./.scripts/deploy.sh
    #     ./.scripts/deploy.sh
    #   shell: bash
